### ISSUE TITLE
[FEATURE] Add an option to just output

### ISSUE THREAD

**Issue by maxjf1** [honsa/simple-stats-webpack-plugin#2]
Great plugin, saving my life.

The problem is, it does much more than just display the stats. 

It also displays an loading and a compile message.

Would be great to have an option to just display the stats (colored or not), when done compiling. That way, i would be able to use it along to the [Progress bar plugin](https://www.npmjs.com/package/progress-bar-webpack-plugin) (currently, the loading animation is overriding it).

I'm using the plugin to display warnings and errors in the watch mode and it's working great. Just this loading animation and conclude message that made me remove other plugins.

(If you stopped support for this package, i can make an PR with this feature, just post below )

**Comment by honsa** [comment]
Thank you, will have a look at time

**Comment by honsa** [comment]
I have published a new version, tell if it fits to your needs now.

You can set the option `showActivity` to hide the loading animation.

https://www.npmjs.com/package/simple-stats-webpack-plugin

**Comment by maxjf1** [comment]
It worked perfectly, thanks! (and thanks for the speed :smile: )
